### ISSUE TITLE
勤怠管理 BOT の作成がうまくいきません。

### ISSUE THREAD

**Issue by k-nakanishi22** [lineworks/samplebot_attendance_management_bot#14]
Traceback (most recent call last):
  File "scripts/initialize.py", line 21, in <module>
    from attendance_management_bot.initDB import init_db
  File "/app/attendance_management_bot/initDB.py", line 29, in <module>
    from attendance_management_bot.constant import DB_CONFIG
ModuleNotFoundError: No module named 'attendance_management_bot.constant'

**Comment by k-nakanishi22** [comment]
サンプルBOTの配布まで進めましたが、Manual deploy から Deploy Branch をクリックしたところ、上記のエラーが吐き出されてしまします。どう修正したらいいのか、教えていただきたいです。

**Comment by k-nakanishi22** [comment]
解決しました。
